#!/usr/bin/env bash
# Bash script which transfere a file from the local machien to the server
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

PATH_TO_FILE=$1
IP=$2
USRNAME=$3
PATH_TO_SSH_KEY=$4

if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i\
	"$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USRNAME"@"$IP":~/
fi
