#!/usr/bin/env bash
# Bash script to install and configure in a baisc level for the nginx web server

# update and upgrade packages
apt-get update -y -q && apt-get upgrade -y -q
# installing nginx pre-requests
apt-get install -y curl

# installing nginx key and setup the download
curl -o nginx_key.key -s https://nginx.org/keys/nginx_signing.key
apt-key add nginx_key.key

echo "deb http://nginx.org/packages/ubuntu/ focal nginx" >> \
     /etc/apt/sources.list
echo "deb-src http://nginx.org/packages/ubuntu/ focal nginx" >> \
     /etc/apt/sources.list

# install nginx
apt-get update
apt-get install -y -q nginx
systemctl start nginx
systemctl enable nginx

# configure nginx default server:
#   Basic setup for the default server configuration
mkdir -p /var/www/html/
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

echo 'server {
    listen       80 default_server;
    server_name  _;

    location / {
        root   /var/www/html;
        index  index.html;
    }
}
' > /etc/nginx/conf.d/default.conf

nginx -s reload
