#!/usr/bin/env bash
# Bash script to install and configure in a baisc level for the nginx web server

# update and upgrade packages
apt-get update -y -q && apt-get upgrade -y -q
# installing nginx pre-requests
apt-get install -y curl

# installing nginx key and setup the download
curl -o nginx_key.key -s https://nginx.org/keys/nginx_signing.key
apt-key add nginx_key.key

# Check if the nginx key is added befor to the apt source list
ADD_NGINX="True"
APT_LIST="/etc/apt/sources.list"
while IFS= read -r line
do
    if [ "$line" == "deb http://nginx.org/packages/ubuntu/ focal nginx" ]
    then
	ADD_NGINX="False"
	break
    fi
done < "$APT_LIST"

if [ "$ADD_NGINX" == "True" ]
then
    echo "deb http://nginx.org/packages/ubuntu/ focal nginx" >> \
	 "$APT_LIST"
    echo "deb-src http://nginx.org/packages/ubuntu/ focal nginx" >> \
	 "$APT_LIST"
fi

# install nginx
apt-get update
apt-get install -y -q nginx
systemctl start nginx
systemctl enable nginx

# configure nginx default server:
#   Basic setup for the default server configuration
mkdir -p /var/www/html/
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

echo "server {
    listen     *:80  default_server;
    error_page 404   /404.html;

    location   / {
        root   /var/www/html;
        index  index.html;
    }

    location = /redirect_me {
        return 301  'Moved Permanently';
    }


}
" > /etc/nginx/conf.d/default.conf

nginx -s reload
