#!/usr/bin/env bash
# Bash script to install and configure in a baisc level for the nginx web server

# update and upgrade packages
apt-get update -y &> /dev/null
# installing nginx pre-requests
apt-get install -y curl &> /dev/null

# install nginx
apt-get install -y nginx &> /dev/null
systemctl start nginx
systemctl enable nginx

# configure nginx default server:
#   Basic setup for the default server configuration
mkdir -p /var/www/html/
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo -e "server {
    listen     80 default_server;
    server_name  54.84.73.143;
    root         /var/www/html;
    error_page   404        /404.html;
    add_header   X-Served-By  \$hostname always;

    location = / {
        index  /index.html;
    }

    location   /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/conf.d/default.conf
sed -i 's/default_server;/;/g' /etc/nginx/sites-enabled/default

service nginx start
nginx -s reload
exit 0
