#!/usr/bin/env bash
## configure load balancer HAProxy for ubuntu machine that will serves
## two servers with roun-robin algrothim

apt update -y &> /dev/null

# install HAProxy
## enable a dedicated PPA
apt-get install -y --no-install-recommends software-properties-common \
    &> /dev/null
add-apt-repository -yu ppa:vbernat/haproxy-2.8 &> /dev/null
## install HAProxy
apt-get install -y haproxy=2.8.\* &> /dev/null

## create directory for the configurations files
mkdir -p /etc/haproxy/haproxy.conf.d

echo -e "ENABLED=1" >> /etc/default/haproxy

service haproxy start

echo -e "\nfrontend web-1
\tbind 0.0.0.0:80
\tdefault_backend web-servers

backend web-servers
\tbalance roundrobin
\tserver web-01 54.84.73.143:80 check
\tserver web-02 35.175.102.250:80 check
" >> /etc/haproxy/haproxy.conf.d/web-01-02_lb.conf

echo -e "include /etc/haproxy/haproxy.conf.d/*.conf" >> /etc/haproxy/haproxy.cfg

service haproxy reload
exit 0
