#!/usr/bin/env bash
# A Bash script to ping an Address provided to the
#+ script as command line argument

ip="$1"

if [[ -z "$ip" ]]
then
    echo 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}'
else
    ping -c 5 "$ip"
fi
