#!/usr/bin/env bash
#A bash script that handle SIGNALS and do cleaning
#+ while runing some statments

trap "echo I hate the kill command" 15
trap "echo Y U no love me?!; rm -f /var/run/myscript.pid; exit" 2

touch "/var/run/myscript.pid"
echo "$$" > "/var/run/myscript.pid"
while true
do
    echo "To infinity and beyond"
done
