#!/usr/bin/env bash
#A bash script that handle SIGNALS and do cleaning
#+ while runing some statments

sudo echo "$$" > "myscript.pid"
sudo mv "myscript.pid" "/var/run/"


while true
do
    trap "echo I hate the kill command" 15
    trap "echo Y U no love me?!; sudo rm -f /var/run/myscript.pid; exit" 2

    echo "To infinity and beyond"
done
