#!/usr/bin/env bash
#A bash script that handle SIGNALS and do cleaning
#+ while runing some statments

echo "$$" > "myscript.pid"
sudo mv "myscript.pid" "/var/run/"


while true
do
    trap "echo I hate the kill command" TERM
    trap "echo Y U no love me?!" INT
    trap "sudo rm -f /var/run/myscript.pid; exit" TERM QUIT

    echo "To infinity and beyond"
done
