#!/usr/bin/env bash
#A bash script that pasre the file /etc/passwd extracting the USERNAME,
#+ GROUP_ID, HOME_DIRECTORY, SHELL, USER_ID, USER_PASSWORD and USER
#+ ID INFO

file="/etc/passwd"

if [[ ! -f "$file" ]]
then
    exit
fi

while read -r line
do
    IFS=':' read -r u ups uid gid uinf uhom ushl <<< "$line"
    echo "The user $u is part of the $gid gang, lives in $uhom and rides $ushl. $uid's place is protected by the passcode $ups, more info about the user here: $uinf"
done < "$file"
