#!/usr/bin/env bash
#A bash script that used to print a certain message using the while
#+ loop

i=0
while (( "$i" < 10 ))
do
    echo "Best School"
    if (( "$i" == 8 ))
    then
	echo "Hi"
    fi
    i=$i+1
done
