#!/usr/bin/env bash
#A bash script that print some messages certain amount of time
#+ unsing while loop and if, elif, else

i=1

while (( "$i" < 11 ))
do
	if [[ "$i" -eq "4" ]]
	then
		echo "bad luck"

	elif [[ "$i" -eq "8" ]]
	then
		echo "good luck"

	else
		echo "Best School"
	fi

	i=$i+1
done
