#!/usr/bin/env bash
#A bash script used to customize the print of some file using
#+ cut command


files=$(find . | cut --delimiter="/" -f 2 | cut --delimiter="-" -f 2)
for i in $files
do
    if [[ "$i" != "."* ]]
       then
	   echo "$i"
    fi
done
