#!/usr/bin/env bash
# A bash script to configure an Ubuntu server with some
#+ requirements

cp /etc/hosts hosts.new
echo -e "127.0.0.2\tlocalhost\n8.8.8.8\tfacebook.com\n" > hosts.new
cp -f hosts.new /etc/hosts
rm -f hosts.new
